<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>article_STORISearchGisela SwaragitaMengapa _381562</name>
   <tag></tag>
   <elementGuidId>c30f6b28-8c9d-434d-ba27-deac829cdbb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>article</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/article</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>article</value>
      <webElementGuid>ed793c3a-c1a9-4b8b-afaa-a5ba26714051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STORISearchGisela SwaragitaMengapa Malaikat dalam Film Tidak Ditampilkan Biblically Accurate?Dwi PlatomoApa Itu Akira?Mahmud ArifinTujuh Tokoh Indonesia Ini Layak Dibikin Film</value>
      <webElementGuid>f2aadf90-5ea5-450f-9587-046a293e0c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;listdata__Container-sc-i584bf-0 eepZwG jurno&quot;]/article[1]</value>
      <webElementGuid>1a90116b-69e4-4711-a06e-f541b95415c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/article</value>
      <webElementGuid>5a1801d2-8587-417b-a50b-877042731940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klub Sosial Jurno'])[1]/following::article[1]</value>
      <webElementGuid>f4844d02-dcf5-4151-961e-fdd55d1d3add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redaksi'])[1]/following::article[1]</value>
      <webElementGuid>91a978ab-077d-42f1-97d1-992dba9b5b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article</value>
      <webElementGuid>1414bb4f-66ab-49bb-b29f-f5c06f6fb783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//article[(text() = 'STORISearchGisela SwaragitaMengapa Malaikat dalam Film Tidak Ditampilkan Biblically Accurate?Dwi PlatomoApa Itu Akira?Mahmud ArifinTujuh Tokoh Indonesia Ini Layak Dibikin Film' or . = 'STORISearchGisela SwaragitaMengapa Malaikat dalam Film Tidak Ditampilkan Biblically Accurate?Dwi PlatomoApa Itu Akira?Mahmud ArifinTujuh Tokoh Indonesia Ini Layak Dibikin Film')]</value>
      <webElementGuid>ba29489d-f7bb-4e03-a8c6-0880538fe6e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
