<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d6c74cf0-50bb-4395-8844-511173e632c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/nav/div/div/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Jurno Website&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>205dd8b1-d97b-4669-b4cd-e29d50f20eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jurno Website</value>
      <webElementGuid>239b5e7b-0cf0-4b6d-9128-525b7ed6a761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>9fc7307a-654c-4780-a8a3-8c77867ffcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/logo-jurno-web-horizontal.svg 640w, /images/logo-jurno-web-horizontal.svg 750w, /images/logo-jurno-web-horizontal.svg 828w, /images/logo-jurno-web-horizontal.svg 1080w, /images/logo-jurno-web-horizontal.svg 1200w, /images/logo-jurno-web-horizontal.svg 1920w, /images/logo-jurno-web-horizontal.svg 2048w, /images/logo-jurno-web-horizontal.svg 3840w</value>
      <webElementGuid>1822eb4b-12c6-4c37-b9bc-c84ac92c2947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo-jurno-web-horizontal.svg</value>
      <webElementGuid>b2b34650-e809-4c8a-88f0-6c74d6f61016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>e4a5b3ab-3a85-4639-9b57-c9992fb0ab93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>bfed3f4c-fe89-4d2f-ab6e-e6e5ccfbbff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;header__Container-sc-14n1q57-0 fJWfAy&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;topbar__Container-sc-11aj7yt-0 GnmNv&quot;]/nav[1]/div[@class=&quot;topbar&quot;]/div[@class=&quot;header-logo jurno&quot;]/a[@class=&quot;link&quot;]/span[1]/img[1]</value>
      <webElementGuid>b883d2f3-d956-45c4-bccb-89a9d5c8b5f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/nav/div/div/a/span/img</value>
      <webElementGuid>cba600c2-2f85-4fad-922b-24db8989c6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Jurno Website']</value>
      <webElementGuid>83d1c4c5-bccb-47d2-889b-da851ec104b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8f5ef2e4-79f6-46db-bf45-b3839d791ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Jurno Website' and @src = '/images/logo-jurno-web-horizontal.svg']</value>
      <webElementGuid>9ae43f4e-81b9-4b09-b4fd-6d830b944e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
